# Generated by Django 5.0.6 on 2024-05-21 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nssapp', '0002_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'admin'), (2, 'nsuser')], default=1, max_length=50),
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('subject', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('file1', models.FileField(blank=True, null=True, upload_to='media/notes/files')),
                ('file2', models.FileField(blank=True, null=True, upload_to='media/notes/files')),
                ('file3', models.FileField(blank=True, null=True, upload_to='media/notes/files')),
                ('file4', models.FileField(blank=True, null=True, upload_to='media/notes/files')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='nssapp.userreg')),
            ],
        ),
    ]
