# Generated by Django 5.0.6 on 2024-05-21 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nssapp', '0003_alter_customuser_user_type_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='description',
            new_name='notesdesc',
        ),
        migrations.RenameField(
            model_name='notes',
            old_name='title',
            new_name='notestitle',
        ),
        migrations.RenameField(
            model_name='notes',
            old_name='user',
            new_name='nsuser',
        ),
    ]
